/*
 * Swagger Petstore
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.pets.core.petstore.data.store.api;

import com.pets.core.petstore.data.store.ApiClient;
import com.pets.core.petstore.data.store.ApiException;
import com.pets.core.petstore.data.store.ApiResponse;
import com.pets.core.petstore.data.store.ApiRequest;
import com.pets.core.petstore.data.store.HttpClientUtils;
import com.pets.core.petstore.data.store.Pair;
import rx.Observable;
import rx.Observer;
import rx.functions.*;
import rx.exceptions.Exceptions;

import com.pets.core.petstore.data.models.Order;

import java.lang.reflect.Type;
import com.google.gson.reflect.TypeToken;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class StoreApi {
    private ApiClient apiClient;

    public StoreApi(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return apiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    /**
     * Delete purchase order by ID (Observable)
     * For valid response try integer IDs with positive integer value. Negative or non-integer values will generate API errors
     * @param orderId ID of the order that needs to be deleted (required)
     * @param callback The callback to be executed when the API call finishes
     * @return Observable<Object> Observable service call
     * Observable.onError will be called with an ApiException if anything about the Request fails, or it is an unsuccessful response.
     */
    public Observable<Object> deleteOrder(Long orderId) {
        Object localVarPostBody = null;
        
        // verify the required parameter 'orderId' is set
        if (orderId == null) {
            return Observable.error(new ApiException("Missing the required parameter 'orderId' when calling deleteOrder"));
        }
        

        // create path and map variables
        String localVarPath = "/store/order/{orderId}".replaceAll("\\{format\\}","json")
        .replaceAll("\\{" + "orderId" + "\\}", HttpClientUtils.escapeString(orderId.toString()));

        // Turn Query Params into Pairs
        List<Pair> localVarQueryParams = new ArrayList<Pair>();

        // Add all generic header params
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        // Setup Form Params
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        // Add Accept Header(s) (if provided)
        final String[] localVarAccepts = {
            "application/xml", "application/json"
        };
        final String localVarAccept = HttpClientUtils.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        // Add Content-Type Header(s) (if provided)
        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = HttpClientUtils.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        String[] localVarAuthNames = new String[] {  };

        // Build final URL for Call
        String endpointWithQuery = apiClient.buildUrl(localVarPath, localVarQueryParams);

        // Build Request
		ApiRequest apiRequest = new ApiRequest("DELETE", localVarHeaderParams, localVarPostBody, localVarFormParams, localVarQueryParams, localVarAuthNames);
        try {
			apiRequest = apiClient.prepareRequestForCall(apiRequest);
        } catch (ApiException e) {
        	return Observable.error(e);
        }



        // Setup Response mapping to generic DTO Type
        final Type localVarReturnType = new TypeToken<Object>(){}.getType();
        return apiClient.DELETE(endpointWithQuery, apiRequest)
            .map(new Func1<ApiResponse, Object>() {
                @Override public Object call(ApiResponse response) {
                    try {
                        return apiClient.handleResponse(response, localVarReturnType);
                    } catch (ApiException e) {
                        throw Exceptions.propagate(e);
                    }
                }
            });

    }

    /**
     * Returns pet inventories by status (Observable)
     * Returns a map of status codes to quantities
     * @param callback The callback to be executed when the API call finishes
     * @return Observable<Map<String, Integer>> Observable service call
     * Observable.onError will be called with an ApiException if anything about the Request fails, or it is an unsuccessful response.
     */
    public Observable<Map<String, Integer>> getInventory() {
        Object localVarPostBody = null;
        

        // create path and map variables
        String localVarPath = "/store/inventory".replaceAll("\\{format\\}","json");

        // Turn Query Params into Pairs
        List<Pair> localVarQueryParams = new ArrayList<Pair>();

        // Add all generic header params
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        // Setup Form Params
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        // Add Accept Header(s) (if provided)
        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = HttpClientUtils.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        // Add Content-Type Header(s) (if provided)
        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = HttpClientUtils.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        String[] localVarAuthNames = new String[] { "api_key" };

        // Build final URL for Call
        String endpointWithQuery = apiClient.buildUrl(localVarPath, localVarQueryParams);

        // Build Request
		ApiRequest apiRequest = new ApiRequest("GET", localVarHeaderParams, localVarPostBody, localVarFormParams, localVarQueryParams, localVarAuthNames);
        try {
			apiRequest = apiClient.prepareRequestForCall(apiRequest);
        } catch (ApiException e) {
        	return Observable.error(e);
        }



        // Setup Response mapping to DTO Type
        final Type localVarReturnType = new TypeToken<Map<String, Integer>>(){}.getType();
        return apiClient.GET(endpointWithQuery, apiRequest)
            .map(new Func1<ApiResponse, Map<String, Integer>>() {
                @Override public Map<String, Integer> call(ApiResponse response) {
                    try {
                        return apiClient.handleResponse(response, localVarReturnType);
                    } catch (ApiException e) {
                        throw Exceptions.propagate(e);
                    }
                }
            });

    }

    /**
     * Find purchase order by ID (Observable)
     * For valid response try integer IDs with value &gt;&#x3D; 1 and &lt;&#x3D; 10. Other values will generated exceptions
     * @param orderId ID of pet that needs to be fetched (required)
     * @param callback The callback to be executed when the API call finishes
     * @return Observable<Order> Observable service call
     * Observable.onError will be called with an ApiException if anything about the Request fails, or it is an unsuccessful response.
     */
    public Observable<Order> getOrderById(Long orderId) {
        Object localVarPostBody = null;
        
        // verify the required parameter 'orderId' is set
        if (orderId == null) {
            return Observable.error(new ApiException("Missing the required parameter 'orderId' when calling getOrderById"));
        }
        

        // create path and map variables
        String localVarPath = "/store/order/{orderId}".replaceAll("\\{format\\}","json")
        .replaceAll("\\{" + "orderId" + "\\}", HttpClientUtils.escapeString(orderId.toString()));

        // Turn Query Params into Pairs
        List<Pair> localVarQueryParams = new ArrayList<Pair>();

        // Add all generic header params
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        // Setup Form Params
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        // Add Accept Header(s) (if provided)
        final String[] localVarAccepts = {
            "application/xml", "application/json"
        };
        final String localVarAccept = HttpClientUtils.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        // Add Content-Type Header(s) (if provided)
        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = HttpClientUtils.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        String[] localVarAuthNames = new String[] {  };

        // Build final URL for Call
        String endpointWithQuery = apiClient.buildUrl(localVarPath, localVarQueryParams);

        // Build Request
		ApiRequest apiRequest = new ApiRequest("GET", localVarHeaderParams, localVarPostBody, localVarFormParams, localVarQueryParams, localVarAuthNames);
        try {
			apiRequest = apiClient.prepareRequestForCall(apiRequest);
        } catch (ApiException e) {
        	return Observable.error(e);
        }



        // Setup Response mapping to DTO Type
        final Type localVarReturnType = new TypeToken<Order>(){}.getType();
        return apiClient.GET(endpointWithQuery, apiRequest)
            .map(new Func1<ApiResponse, Order>() {
                @Override public Order call(ApiResponse response) {
                    try {
                        return apiClient.handleResponse(response, localVarReturnType);
                    } catch (ApiException e) {
                        throw Exceptions.propagate(e);
                    }
                }
            });

    }

    /**
     * Place an order for a pet (Observable)
     * 
     * @param body order placed for purchasing the pet (required)
     * @param callback The callback to be executed when the API call finishes
     * @return Observable<Order> Observable service call
     * Observable.onError will be called with an ApiException if anything about the Request fails, or it is an unsuccessful response.
     */
    public Observable<Order> placeOrder(Order body) {
        Object localVarPostBody = body;
        
        // verify the required parameter 'body' is set
        if (body == null) {
            return Observable.error(new ApiException("Missing the required parameter 'body' when calling placeOrder"));
        }
        

        // create path and map variables
        String localVarPath = "/store/order".replaceAll("\\{format\\}","json");

        // Turn Query Params into Pairs
        List<Pair> localVarQueryParams = new ArrayList<Pair>();

        // Add all generic header params
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        // Setup Form Params
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        // Add Accept Header(s) (if provided)
        final String[] localVarAccepts = {
            "application/xml", "application/json"
        };
        final String localVarAccept = HttpClientUtils.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        // Add Content-Type Header(s) (if provided)
        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = HttpClientUtils.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        String[] localVarAuthNames = new String[] {  };

        // Build final URL for Call
        String endpointWithQuery = apiClient.buildUrl(localVarPath, localVarQueryParams);

        // Build Request
		ApiRequest apiRequest = new ApiRequest("POST", localVarHeaderParams, localVarPostBody, localVarFormParams, localVarQueryParams, localVarAuthNames);
        try {
			apiRequest = apiClient.prepareRequestForCall(apiRequest);
        } catch (ApiException e) {
        	return Observable.error(e);
        }



        // Setup Response mapping to DTO Type
        final Type localVarReturnType = new TypeToken<Order>(){}.getType();
        return apiClient.POST(endpointWithQuery, apiRequest)
            .map(new Func1<ApiResponse, Order>() {
                @Override public Order call(ApiResponse response) {
                    try {
                        return apiClient.handleResponse(response, localVarReturnType);
                    } catch (ApiException e) {
                        throw Exceptions.propagate(e);
                    }
                }
            });

    }

}
