/**
 * Swagger Petstore
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.pets.core.petstore.data.store.store.api;

import com.pets.core.petstore.data.store.ApiClient;
import com.pets.core.petstore.data.store.ApiException;
import com.pets.core.petstore.data.store.ApiResponse;
import com.pets.core.petstore.data.store.Configuration;
import com.pets.core.petstore.data.store.Pair;

import com.pets.core.petstore.data.models.Pet;
import com.pets.core.petstore.data.models.ModelApiResponse;
import java.io.File;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class PetApi {
    private ApiClient apiClient;

    public PetApi() {
        this(Configuration.getDefaultApiClient());
    }

    public PetApi(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return apiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public Observable<Void> addPet(Pet body) {
        Object localVarPostBody = body;
        
        // verify the required parameter 'body' is set
        // TODO OnError instead of Throw
        if (body == null) {
            throw new ApiException("Missing the required parameter 'body' when calling addPet(Async)");
        }
        

        // create path and map variables
        String localVarPath = "pet".replaceAll("\\{format\\}","json");

        // Turn Query Params into Pairs
        List<Pair> localVarQueryParams = new ArrayList<Pair>();

        // Add all generic header params
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        // Setup Form Params
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        // Add Accept Header(s) (if provided)
        final String[] localVarAccepts = {
            "application/xml", "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        // Add Content-Type Header(s) (if provided)
        final String[] localVarContentTypes = {
            "application/json", "application/xml"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        String endpointWithQuery = apiClient.buildUrl(localVarPath, localVarQueryParams);

        Type localVarReturnType = new TypeToken<Void>(){}.getType();

		ApiRequest apiRequest = new ApiRequest("POST", localVarHeaderParams, localVarPostBody, localVarFormParams, localVarQueryParams);
        apiRequest = apiClient.prepareRequestForCall(apiRequest);
		return apiClient.(endpointWithQuery, apiRequest)
		   .map( response -> apiClient.handleResponse(response, localVarReturnType) );

    }

    public Observable<Void> deletePet(Long petIdString apiKey) {
        Object localVarPostBody = null;
        
        // verify the required parameter 'petId' is set
        // TODO OnError instead of Throw
        if (petId == null) {
            throw new ApiException("Missing the required parameter 'petId' when calling deletePet(Async)");
        }
        

        // create path and map variables
        String localVarPath = "pet/{petId}".replaceAll("\\{format\\}","json")
        .replaceAll("\\{" + "petId" + "\\}", apiClient.escapeString(petId.toString()));

        // Turn Query Params into Pairs
        List<Pair> localVarQueryParams = new ArrayList<Pair>();

        // Add all generic header params
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        if (apiKey != null)
        localVarHeaderParams.put("api_key", apiClient.parameterToString(apiKey));

        // Setup Form Params
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        // Add Accept Header(s) (if provided)
        final String[] localVarAccepts = {
            "application/xml", "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        // Add Content-Type Header(s) (if provided)
        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        String endpointWithQuery = apiClient.buildUrl(localVarPath, localVarQueryParams);

        Type localVarReturnType = new TypeToken<Void>(){}.getType();

		ApiRequest apiRequest = new ApiRequest("DELETE", localVarHeaderParams, localVarPostBody, localVarFormParams, localVarQueryParams);
        apiRequest = apiClient.prepareRequestForCall(apiRequest);
		return apiClient.(endpointWithQuery, apiRequest)
		   .map( response -> apiClient.handleResponse(response, localVarReturnType) );

    }

    public Observable<List<Pet>> findPetsByStatus(List<String> status) {
        Object localVarPostBody = null;
        
        // verify the required parameter 'status' is set
        // TODO OnError instead of Throw
        if (status == null) {
            throw new ApiException("Missing the required parameter 'status' when calling findPetsByStatus(Async)");
        }
        

        // create path and map variables
        String localVarPath = "pet/findByStatus".replaceAll("\\{format\\}","json");

        // Turn Query Params into Pairs
        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        if (status != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("multi", "status", status));

        // Add all generic header params
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        // Setup Form Params
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        // Add Accept Header(s) (if provided)
        final String[] localVarAccepts = {
            "application/xml", "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        // Add Content-Type Header(s) (if provided)
        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        String endpointWithQuery = apiClient.buildUrl(localVarPath, localVarQueryParams);

        Type localVarReturnType = new TypeToken<List<Pet>>(){}.getType();

		ApiRequest apiRequest = new ApiRequest("GET", localVarHeaderParams, localVarPostBody, localVarFormParams, localVarQueryParams);
        apiRequest = apiClient.prepareRequestForCall(apiRequest);
		return apiClient.(endpointWithQuery, apiRequest)
		   .map( response -> apiClient.handleResponse(response, localVarReturnType) );

    }

    public Observable<List<Pet>> findPetsByTags(List<String> tags) {
        Object localVarPostBody = null;
        
        // verify the required parameter 'tags' is set
        // TODO OnError instead of Throw
        if (tags == null) {
            throw new ApiException("Missing the required parameter 'tags' when calling findPetsByTags(Async)");
        }
        

        // create path and map variables
        String localVarPath = "pet/findByTags".replaceAll("\\{format\\}","json");

        // Turn Query Params into Pairs
        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        if (tags != null)
        localVarQueryParams.addAll(apiClient.parameterToPairs("multi", "tags", tags));

        // Add all generic header params
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        // Setup Form Params
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        // Add Accept Header(s) (if provided)
        final String[] localVarAccepts = {
            "application/xml", "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        // Add Content-Type Header(s) (if provided)
        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        String endpointWithQuery = apiClient.buildUrl(localVarPath, localVarQueryParams);

        Type localVarReturnType = new TypeToken<List<Pet>>(){}.getType();

		ApiRequest apiRequest = new ApiRequest("GET", localVarHeaderParams, localVarPostBody, localVarFormParams, localVarQueryParams);
        apiRequest = apiClient.prepareRequestForCall(apiRequest);
		return apiClient.(endpointWithQuery, apiRequest)
		   .map( response -> apiClient.handleResponse(response, localVarReturnType) );

    }

    public Observable<Pet> getPetById(Long petId) {
        Object localVarPostBody = null;
        
        // verify the required parameter 'petId' is set
        // TODO OnError instead of Throw
        if (petId == null) {
            throw new ApiException("Missing the required parameter 'petId' when calling getPetById(Async)");
        }
        

        // create path and map variables
        String localVarPath = "pet/{petId}".replaceAll("\\{format\\}","json")
        .replaceAll("\\{" + "petId" + "\\}", apiClient.escapeString(petId.toString()));

        // Turn Query Params into Pairs
        List<Pair> localVarQueryParams = new ArrayList<Pair>();

        // Add all generic header params
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        // Setup Form Params
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        // Add Accept Header(s) (if provided)
        final String[] localVarAccepts = {
            "application/xml", "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        // Add Content-Type Header(s) (if provided)
        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        String endpointWithQuery = apiClient.buildUrl(localVarPath, localVarQueryParams);

        Type localVarReturnType = new TypeToken<Pet>(){}.getType();

		ApiRequest apiRequest = new ApiRequest("GET", localVarHeaderParams, localVarPostBody, localVarFormParams, localVarQueryParams);
        apiRequest = apiClient.prepareRequestForCall(apiRequest);
		return apiClient.(endpointWithQuery, apiRequest)
		   .map( response -> apiClient.handleResponse(response, localVarReturnType) );

    }

    public Observable<Void> updatePet(Pet body) {
        Object localVarPostBody = body;
        
        // verify the required parameter 'body' is set
        // TODO OnError instead of Throw
        if (body == null) {
            throw new ApiException("Missing the required parameter 'body' when calling updatePet(Async)");
        }
        

        // create path and map variables
        String localVarPath = "pet".replaceAll("\\{format\\}","json");

        // Turn Query Params into Pairs
        List<Pair> localVarQueryParams = new ArrayList<Pair>();

        // Add all generic header params
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        // Setup Form Params
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        // Add Accept Header(s) (if provided)
        final String[] localVarAccepts = {
            "application/xml", "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        // Add Content-Type Header(s) (if provided)
        final String[] localVarContentTypes = {
            "application/json", "application/xml"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        String endpointWithQuery = apiClient.buildUrl(localVarPath, localVarQueryParams);

        Type localVarReturnType = new TypeToken<Void>(){}.getType();

		ApiRequest apiRequest = new ApiRequest("PUT", localVarHeaderParams, localVarPostBody, localVarFormParams, localVarQueryParams);
        apiRequest = apiClient.prepareRequestForCall(apiRequest);
		return apiClient.(endpointWithQuery, apiRequest)
		   .map( response -> apiClient.handleResponse(response, localVarReturnType) );

    }

    public Observable<Void> updatePetWithForm(Long petIdString nameString status) {
        Object localVarPostBody = null;
        
        // verify the required parameter 'petId' is set
        // TODO OnError instead of Throw
        if (petId == null) {
            throw new ApiException("Missing the required parameter 'petId' when calling updatePetWithForm(Async)");
        }
        

        // create path and map variables
        String localVarPath = "pet/{petId}".replaceAll("\\{format\\}","json")
        .replaceAll("\\{" + "petId" + "\\}", apiClient.escapeString(petId.toString()));

        // Turn Query Params into Pairs
        List<Pair> localVarQueryParams = new ArrayList<Pair>();

        // Add all generic header params
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        // Setup Form Params
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();
        if (name != null)
        localVarFormParams.put("name", name);
        if (status != null)
        localVarFormParams.put("status", status);

        // Add Accept Header(s) (if provided)
        final String[] localVarAccepts = {
            "application/xml", "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        // Add Content-Type Header(s) (if provided)
        final String[] localVarContentTypes = {
            "application/x-www-form-urlencoded"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        String endpointWithQuery = apiClient.buildUrl(localVarPath, localVarQueryParams);

        Type localVarReturnType = new TypeToken<Void>(){}.getType();

		ApiRequest apiRequest = new ApiRequest("POST", localVarHeaderParams, localVarPostBody, localVarFormParams, localVarQueryParams);
        apiRequest = apiClient.prepareRequestForCall(apiRequest);
		return apiClient.(endpointWithQuery, apiRequest)
		   .map( response -> apiClient.handleResponse(response, localVarReturnType) );

    }

    public Observable<ModelApiResponse> uploadFile(Long petIdString additionalMetadataFile file) {
        Object localVarPostBody = null;
        
        // verify the required parameter 'petId' is set
        // TODO OnError instead of Throw
        if (petId == null) {
            throw new ApiException("Missing the required parameter 'petId' when calling uploadFile(Async)");
        }
        

        // create path and map variables
        String localVarPath = "pet/{petId}/uploadImage".replaceAll("\\{format\\}","json")
        .replaceAll("\\{" + "petId" + "\\}", apiClient.escapeString(petId.toString()));

        // Turn Query Params into Pairs
        List<Pair> localVarQueryParams = new ArrayList<Pair>();

        // Add all generic header params
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        // Setup Form Params
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();
        if (additionalMetadata != null)
        localVarFormParams.put("additionalMetadata", additionalMetadata);
        if (file != null)
        localVarFormParams.put("file", file);

        // Add Accept Header(s) (if provided)
        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        // Add Content-Type Header(s) (if provided)
        final String[] localVarContentTypes = {
            "multipart/form-data"
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        String endpointWithQuery = apiClient.buildUrl(localVarPath, localVarQueryParams);

        Type localVarReturnType = new TypeToken<ModelApiResponse>(){}.getType();

		ApiRequest apiRequest = new ApiRequest("POST", localVarHeaderParams, localVarPostBody, localVarFormParams, localVarQueryParams);
        apiRequest = apiClient.prepareRequestForCall(apiRequest);
		return apiClient.(endpointWithQuery, apiRequest)
		   .map( response -> apiClient.handleResponse(response, localVarReturnType) );

    }

}
